// lang.js
window.translations = {
  "en": {
    "pageTitle": "Padaria Branco Quente | Artisan Bakery in Monchique",
    "navHome": "Home",
    "navMenu": "Menu",
    "navAbout": "About Us",
    "navContact": "Contact",
    "heroTitle": "Artisan Bakery of Monchique",
    "heroSubtitle": "Traditional Portuguese breads and pastries made with love since 1987",
    "heroButton": "View Menu",
    "aboutImageCaption": "Cozy interior of our artisan bakery.",
    "aboutTitle": "Our History",
    "aboutDesc1": "Founded in the heart of Monchique, Padaria Branco Quente has been serving the community with traditional Portuguese products for over three decades.",
    "aboutDesc2": "We use only the best local ingredients: flour from Alentejo and eggs from free-range chickens in the Algarve.",
    "aboutFeature1": "Wood-fired oven",
    "aboutFeature2": "Organic ingredients",
    "aboutFeature3": "Family recipes",
    "aboutFeature4": "Fresh every day",
    "productsTitle": "Our Specialties",
    "productsSubtitle": "Discover the products that make our customers return every day",
    "product1Title": "Pão de Monchique",
    "product1Desc": "Our most emblematic bread, with a crispy crust and soft crumb, baked in a wood-fired oven.",
    "product2Title": "Pastel de Nata",
    "product2Desc": "Delicious custard tarts with crispy puff pastry and sprinkled with cinnamon.",
    "product3Title": "Honey Cake",
    "product3Desc": "Traditional honey cake from the Algarve, enriched with local almonds.",
    "productsButton": "View Full Menu",
    "ctaTitle": "Visit Our Bakery in Monchique",
    "ctaSubtitle": "We bake fresh bread every morning starting at 5 am. Come smell the aroma!",
    "ctaButton1": "Get Directions",
    "ctaButton2": "Contact Us",
    "footerDesc": "Traditional Portuguese bakery in Monchique since 1987.",
    "footerNavTitle": "Navigation",
    "footerHoursTitle": "Opening Hours",
    "footerHours1": "Monday - Friday: 6am - 7pm",
    "footerHours2": "Saturday: 6am - 5pm",
    "footerHours3": "Sunday: 7am - 2pm",
    "footerFollowTitle": "Follow Us",
    "footerCopyright": "&copy; 2023 Padaia Deliciosa. All rights reserved.",
    
    "menuPageTitle": "Menu | Padaria Branco Quente",
    "menuHeaderTitle": "Our Menu",
    "menuHeaderSubtitle": "Traditional Portuguese bakery products made with love and local ingredients",
    "menuBreadsTitle": "Breads",
    "menuBread1Title": "Pão de Monchique",
    "menuBread1Desc": "Our wood-fired oven bread with a crispy crust and fluffy crumb.",
    "menuBread2Title": "Pão Alentejano",
    "menuBread2Desc": "Traditional round bread from Alentejo, with a dense crumb and authentic flavor.",
    "menuBread3Title": "Rye Bread",
    "menuBread3Desc": "Robust rye bread, with an intense flavor and consistent texture.",
    "menuPastriesTitle": "Pastries",
    "menuPastry1Title": "Pastel de Nata",
    "menuPastry1Desc": "Creamy custard tarts with crispy puff pastry and a touch of cinnamon.",
    "menuPastry1Price": "€1.20 each",
    "menuPastry2Title": "Bolo de Arroz",
    "menuPastry2Desc": "Rice flour muffins with a light texture and delicate flavor.",
    "menuPastry2Price": "€1.00 each",
    "menuPastry3Title": "Honey Cake",
    "menuPastry3Desc": "Algarve honey cake, enriched with local honey and almonds.",
    "menuPastry3Price": "€3.50 (slice)",
    "menuDrinksTitle": "Drinks",
    "menuDrink1Title": "Bica (Espresso)",
    "menuDrink1Desc": "Intense Portuguese-style espresso, made with selected beans.",
    "menuDrink2Title": "Galão",
    "menuDrink2Desc": "Coffee with milk served in a tall glass, perfect with a pastry.",
    "menuDrink3Title": "Fruit Juice",
    "menuDrink3Desc": "Natural juices from fresh Algarve fruits, squeezed to order.",

    "aboutPageTitle": "About Us | Padaria Branco Quente",
    "aboutHeroTitle": "Our History",
    "aboutHeroSubtitle": "Three generations of tradition in Monchique",
    "aboutFig1Caption": "Our first bakery in Monchique.",
    "aboutStoryTitle": "From Humble Beginnings",
    "aboutStoryDesc1": "Founded in 1987 by João and Maria Silva, Padaria Deliciosa started as a small neighborhood bakery serving fresh bread to the people of Monchique.",
    "aboutStoryDesc2": "What began as a modest wood-fired oven has grown into a local institution, now managed by daughter Ana and her husband Carlos, who continue the family tradition with a modern touch.",
    "aboutStoryFact": "Open every day since 1987",
    "aboutMissionTitle": "Our Mission & Values",
    "aboutMissionDesc": "At Padaria Deliciosa, we believe in preserving Portuguese traditions, using only the best local ingredients. Our commitment to quality has remained unchanged for over three decades.",
    "aboutValue1Title": "Passion",
    "aboutValue1Desc": "We make every loaf and cake with love and dedication.",
    "aboutValue2Title": "Quality",
    "aboutValue2Desc": "We use only excellent local ingredients.",
    "aboutValue3Title": "Community",
    "aboutValue3Desc": "Proudly serving Monchique since 1987.",
    "aboutTeamTitle": "Our Team",
    "aboutTeamSubtitle": "The faces behind your favorite products.",
    "aboutTeam1FigCap": "Ana Silva in the bakery.",
    "aboutTeam1Name": "Ana Silva",
    "aboutTeam1Role": "Owner & Baker",
    "aboutTeam1Desc": "Daughter of the founders, she grew up in the bakery and studied pastry in Lisbon before taking over the family business.",
    "aboutTeam2FigCap": "Carlos preparing traditional sweets.",
    "aboutTeam2Name": "Carlos Mendes",
    "aboutTeam2Role": "Pastry Chef",
    "aboutTeam2Desc": "Specialist in traditional Portuguese pastry, with over 20 years of experience.",
    "aboutTeam3FigCap": "Miguel by the wood-fired oven.",
    "aboutTeam3Name": "Miguel Costa",
    "aboutTeam3Role": "Master Baker",
    "aboutTeam3Desc": "Our wood-fired oven specialist who starts baking bread at 3 am.",
    "aboutCtaTitle": "Visit Our Bakery",
    "aboutCtaSubtitle": "Come experience the tradition and taste of true Portuguese baking.",
    "aboutCtaBtn1": "View Menu",
    "aboutCtaBtn2": "Contact Us",

    "contactPageTitle": "Contact | Padaria Branco Quente",
    "contactHeroTitle": "Contact Us",
    "contactHeroSubtitle": "We would love to hear from you",
    "contactFormTitle": "Send Us a Message",
    "contactFormName": "Your name",
    "contactFormEmail": "Email address",
    "contactFormMessage": "Your message",
    "contactFormButton": "Send Message",
    "contactMapPlaceholder1": "Google Maps will appear here",
    "contactMapPlaceholder2": "showing our bakery's location in Monchique",
    "contactInfoTitle": "Visit Our Bakery",
    "contactInfoAddressTitle": "Address",
    "contactInfoPhoneTitle": "Phone",
    "contactInfoEmailTitle": "Email",
    "contactInfoHoursTitle": "Opening Hours",
    "contactInfoHoursDesc": "Mon-Fri: 6am - 7pm<br>Sat: 6am - 5pm<br>Sun: 7am - 2pm",
    "contactInfoFollowTitle": "Follow Us"
  },
  "pt": {
    "pageTitle": "Padaria Branco Quente | Padaria Artesanal em Monchique",
    "navHome": "Início",
    "navMenu": "Menu",
    "navAbout": "Sobre Nós",
    "navContact": "Contacto",
    "heroTitle": "Padaria Artesanal de Monchique",
    "heroSubtitle": "Pães e doces tradicionais portugueses feitos com amor desde 1987",
    "heroButton": "Ver Menu",
    "aboutImageCaption": "Interior acolhedor da nossa padaria artesanal.",
    "aboutTitle": "A Nossa História",
    "aboutDesc1": "Fundada no coração de Monchique, a Padaria Branco Quente serve a comunidade com produtos tradicionais portugueses há mais de três décadas.",
    "aboutDesc2": "Usamos apenas os melhores ingredientes locais: farinha do Alentejo e ovos de galinhas criadas ao ar livre no Algarve.",
    "aboutFeature1": "Forno a lenha",
    "aboutFeature2": "Ingredientes biológicos",
    "aboutFeature3": "Receitas de família",
    "aboutFeature4": "Fresco todos os dias",
    "productsTitle": "As Nossas Especialidades",
    "productsSubtitle": "Descubra os produtos que fazem os nossos clientes regressar todos os dias",
    "product1Title": "Pão de Monchique",
    "product1Desc": "O nosso pão mais emblemático, com crosta estaladiça e miolo macio, cozido em forno a lenha.",
    "product2Title": "Pastel de Nata",
    "product2Desc": "Deliciosas tartes de nata com massa folhada crocante e polvilhadas com canela.",
    "product3Title": "Bolo de Mel",
    "product3Desc": "Bolo tradicional de mel do Algarve, enriquecido com amêndoas locais.",
    "productsButton": "Ver Menu Completo",
    "ctaTitle": "Visite a Nossa Padaria em Monchique",
    "ctaSubtitle": "Cozemos pão fresco todas as manhãs a partir das 5h. Venha sentir o aroma!",
    "ctaButton1": "Obter Direções",
    "ctaButton2": "Contactar",
    "footerDesc": "Padaria tradicional portuguesa em Monchique desde 1987.",
    "footerNavTitle": "Navegação",
    "footerHoursTitle": "Horário",
    "footerHours1": "Segunda - Sexta: 6h - 19h",
    "footerHours2": "Sábado: 6h - 17h",
    "footerHours3": "Domingo: 7h - 14h",
    "footerFollowTitle": "Siga-nos",
    "footerCopyright": "&copy; 2023 Padaia Deliciosa. Todos os direitos reservados.",

    "menuPageTitle": "Menu | Padaria Branco Quente",
    "menuHeaderTitle": "O Nosso Menu",
    "menuHeaderSubtitle": "Produtos de padaria tradicionais portugueses feitos com amor e ingredientes locais",
    "menuBreadsTitle": "Pães",
    "menuBread1Title": "Pão de Monchique",
    "menuBread1Desc": "O nosso pão de forno a lenha com crosta estaladiça e miolo fofo.",
    "menuBread2Title": "Pão Alentejano",
    "menuBread2Desc": "Pão redondo tradicional do Alentejo, com miolo denso e sabor autêntico.",
    "menuBread3Title": "Pão de Centeio",
    "menuBread3Desc": "Pão de centeio robusto, com sabor intenso e textura consistente.",
    "menuPastriesTitle": "Pastéis",
    "menuPastry1Title": "Pastel de Nata",
    "menuPastry1Desc": "Tartes de nata cremosas com massa folhada crocante e toque de canela.",
    "menuPastry1Price": "€1,20 cada",
    "menuPastry2Title": "Bolo de Arroz",
    "menuPastry2Desc": "Queques de farinha de arroz com textura leve e sabor delicado.",
    "menuPastry2Price": "€1,00 cada",
    "menuPastry3Title": "Bolo de Mel",
    "menuPastry3Desc": "Bolo de mel do Algarve, enriquecido com mel local e amêndoas.",
    "menuPastry3Price": "€3,50 (fatia)",
    "menuDrinksTitle": "Bebidas",
    "menuDrink1Title": "Bica (Expresso)",
    "menuDrink1Desc": "Expresso intenso ao estilo português, feito com grãos selecionados.",
    "menuDrink2Title": "Galão",
    "menuDrink2Desc": "Café com leite servido em copo alto, perfeito para acompanhar um pastel.",
    "menuDrink3Title": "Sumo de Fruta",
    "menuDrink3Desc": "Sumos naturais de frutas frescas do Algarve, espremidas na hora.",

    "aboutPageTitle": "Sobre Nós | Padaria Branco Quente",
    "aboutHeroTitle": "A Nossa História",
    "aboutHeroSubtitle": "Três gerações de tradição em Monchique",
    "aboutFig1Caption": "A nossa primeira padaria em Monchique.",
    "aboutStoryTitle": "Das Origens Simples",
    "aboutStoryDesc1": "Fundada em 1987 por João e Maria Silva, a Padaria Deliciosa começou como uma pequena padaria de bairro a servir pão fresco aos habitantes de Monchique.",
    "aboutStoryDesc2": "O que começou como um forno a lenha modesto cresceu para se tornar uma instituição local, agora gerida pela filha Ana e pelo marido Carlos, que continuam a tradição familiar com um toque moderno.",
    "aboutStoryFact": "Aberta todos os dias desde 1987",
    "aboutMissionTitle": "A Nossa Missão & Valores",
    "aboutMissionDesc": "Na Padaria Deliciosa acreditamos em preservar as tradições portuguesas, usando apenas os melhores ingredientes locais. O nosso compromisso com a qualidade mantém-se inalterado há mais de três décadas.",
    "aboutValue1Title": "Paixão",
    "aboutValue1Desc": "Fazemos cada pão e bolo com amor e dedicação.",
    "aboutValue2Title": "Qualidade",
    "aboutValue2Desc": "Usamos apenas ingredientes locais de excelência.",
    "aboutValue3Title": "Comunidade",
    "aboutValue3Desc": "A servir Monchique com orgulho desde 1987.",
    "aboutTeamTitle": "A Nossa Equipa",
    "aboutTeamSubtitle": "Os rostos por trás dos seus produtos favoritos.",
    "aboutTeam1FigCap": "Ana Silva na padaria.",
    "aboutTeam1Name": "Ana Silva",
    "aboutTeam1Role": "Proprietária & Padeira",
    "aboutTeam1Desc": "Filha dos fundadores, cresceu na padaria e estudou pastelaria em Lisboa antes de assumir o negócio da família.",
    "aboutTeam2FigCap": "Carlos a preparar doçaria tradicional.",
    "aboutTeam2Name": "Carlos Mendes",
    "aboutTeam2Role": "Pasteleiro",
    "aboutTeam2Desc": "Especialista em pastelaria tradicional portuguesa, com mais de 20 anos de experiência.",
    "aboutTeam3FigCap": "Miguel junto ao forno a lenha.",
    "aboutTeam3Name": "Miguel Costa",
    "aboutTeam3Role": "Mestre Padeiro",
    "aboutTeam3Desc": "O nosso especialista em forno a lenha que começa a cozer pão às 3 da manhã.",
    "aboutCtaTitle": "Visite a Nossa Padaria",
    "aboutCtaSubtitle": "Venha experimentar a tradição e o sabor da verdadeira padaria portuguesa.",
    "aboutCtaBtn1": "Ver Menu",
    "aboutCtaBtn2": "Fale Connosco",
    
    "contactPageTitle": "Contactos | Padaria Branco Quente",
    "contactHeroTitle": "Contacte-nos",
    "contactHeroSubtitle": "Gostaríamos muito de ouvir a sua opinião",
    "contactFormTitle": "Envie-nos uma Mensagem",
    "contactFormName": "O seu nome",
    "contactFormEmail": "Endereço de email",
    "contactFormMessage": "A sua mensagem",
    "contactFormButton": "Enviar Mensagem",
    "contactMapPlaceholder1": "Aqui aparecerá o Google Maps",
    "contactMapPlaceholder2": "a mostrar a localização da nossa padaria em Monchique",
    "contactInfoTitle": "Visite a Nossa Padaria",
    "contactInfoAddressTitle": "Morada",
    "contactInfoPhoneTitle": "Telefone",
    "contactInfoEmailTitle": "Email",
    "contactInfoHoursTitle": "Horário",
    "contactInfoHoursDesc": "Seg-Sex: 6h - 19h<br>Sáb: 6h - 17h<br>Dom: 7h - 14h",
    "contactInfoFollowTitle": "Siga-nos"
  }
};
